### ISSUE TITLE
Cannot convert using the CLI

### ISSUE THREAD

**Issue by kylegibson** [CenterForOpenScience/pydocx#197]
No matter what arguments are passed to the CLI, it always fails.

```
$ pydocx --html document.docx output.html
Usage: pydocx --html|--markdown input.docx output
```

The reason because in `setup.py` we specify the entry-point function as `main`, so this by passes the `if` conditional in `__main__.py` which would otherwise correctly pull the arguments from `sys.argv`.

**Comment by IuryAlves** [comment]
Maybe it's a good ideia refactor to use argparse instead of sys.argv =D

**Comment by jlward** [comment]
We should also write at least one test that converts a document using the command line tool (`subprocess32` FTW). This is not the first time we broke the CLI

**Comment by two7sclash** [comment]
Work around or date for fixed release?

**Comment by winhamwr** [comment]
Hi James,

> Work around or date for fixed release?

You can work around this by writing your own simple python script that looks very similar to [__main__](https://github.com/CenterForOpenScience/pydocx/blob/master/pydocx/__main__.py) and then calling that script in leu of the script bundled with pydocx.

If this is currently blocking you, we'd really appreciate it if you could create a pull request to fix the issue in the master branch. I'm sure it's blocking other people, too. We could get your PR reviewed and merged in within a day or two, if you were willing to do that. We could then push a fixed release to pypi for you.

Otherwise, my guess is that the end of this week would be the earliest prospect of @jlward being able to prioritize time to work on this, but that's not guaranteed (and Jason would know better than me what his priority list looks like).

Thanks
-Wes

**Comment by two7sclash** [comment]
Ok, cool, thanks! I'll create the request.

**Comment by winhamwr** [comment]
> I'll create the request.

Excellent! Thank you.

I personally like [this structure](https://chriswarrick.com/blog/2014/09/15/python-apps-the-right-way-entry_points-and-scripts/) better than the way we do things now. Basically, make `main()` accept an optional `args` argument, the defaults to reading `sys.argv[1:]` if args is None. Then, we can simplify the `if __name__ == "__main__"` check.

-Wes

**Comment by winhamwr** [comment]
@jlward I spent ~10 minutes searching around for non-hacky (or even just reasonably hacky) ways to use subprocess to test the entry point `console_scripts` directly, but I didn't have any luck. If someone else can figure out how to do that, it would make this less likely to regress in the future, but I don't want to make figuring that out a blocker for getting a fixed CLI call merged in. Feel free to correct me if I'm wrong about how difficult that is or about the trade-off.
